apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: infra
spec:
  kafka:
    version: 3.6.0
    replicas: 3
    metadataStorage:
      type: kraft
    storage:
      type: persistent-claim
      size: 10Gi
      class: standard
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
    config:
      process.roles: broker,controller
      node.id: ${STRIMZI_KAFKA_NODE_ID}
      controller.listener.names: CONTROLLER
      controller.quorum.voters: ${STRIMZI_KRAFT_CONTROLLER_QUORUM_VOTERS}
      listener.security.protocol.map: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      inter.broker.listener.name: INTERNAL
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: "false"
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  entityOperator:
    topicOperator: {}
    userOperator: {}