apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: payment-request
  namespace: infra
  labels:
    strimzi.io/cluster: kafka-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: "604800000" # 7 g√ºn
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: soap-ready
  namespace: infra
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: approval-result
  namespace: infra
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    min.insync.replicas: 2
