apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: monitoring
    version: 58.2.2
    namespace: infra
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    version: 2.10.2
    namespace: infra
