apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BurakCokluk/rest2soap
    targetRevision: main
    path: infrastructure/kubernetes
    directory:
      recurse: true
      exclude: "{apps/**}"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
