image:
  repository: ghcr.io/burak/rest-api
  tag: "latest"

replicaCount: 1

env:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap.infra.svc:9092"
  KAFKA_TOPIC_OUT: "payment_request"
  KAFKA_GROUP_ID: "rest-api"
  PORT: "8080"

